// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVFp3KVIDwCKcVloJVzO154LcNGBZvBmg',
    appId: '1:940838402518:web:472b45208951a09feb8c77',
    messagingSenderId: '940838402518',
    projectId: 'clothesapp-28a13',
    authDomain: 'clothesapp-28a13.firebaseapp.com',
    storageBucket: 'clothesapp-28a13.firebasestorage.app',
    measurementId: 'G-3C2Y382S95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvGBE9LjgiXHI_IWtFHK-xVITh8SnL7xc',
    appId: '1:940838402518:android:7b750a2bec633654eb8c77',
    messagingSenderId: '940838402518',
    projectId: 'clothesapp-28a13',
    storageBucket: 'clothesapp-28a13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8aH83DmmT8nilYK_B-wGTIwspzkFOwfU',
    appId: '1:940838402518:ios:e4ae6ae136df320beb8c77',
    messagingSenderId: '940838402518',
    projectId: 'clothesapp-28a13',
    storageBucket: 'clothesapp-28a13.firebasestorage.app',
    iosBundleId: 'com.example.clothesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8aH83DmmT8nilYK_B-wGTIwspzkFOwfU',
    appId: '1:940838402518:ios:e4ae6ae136df320beb8c77',
    messagingSenderId: '940838402518',
    projectId: 'clothesapp-28a13',
    storageBucket: 'clothesapp-28a13.firebasestorage.app',
    iosBundleId: 'com.example.clothesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVFp3KVIDwCKcVloJVzO154LcNGBZvBmg',
    appId: '1:940838402518:web:16ace7eb084301a0eb8c77',
    messagingSenderId: '940838402518',
    projectId: 'clothesapp-28a13',
    authDomain: 'clothesapp-28a13.firebaseapp.com',
    storageBucket: 'clothesapp-28a13.firebasestorage.app',
    measurementId: 'G-XBPZ5VSPMK',
  );
}
